### ISSUE TITLE
seed ="" always the same secret

### ISSUE THREAD

**Issue by yujingyue9166** [unicredit/mosaic#2]
In case seed ="", I expect to get  a random secret, but I always get the same secret every time. And I wonder why the secret needs to be a point.

**Comment by marcellop71** [comment]
Thank you for pointing out. My bad: sloppy mngmt of seed and hash-to-group (I left a if branch incomplete and HashToGroup was called when seed != "").
Pushed a fix: introduced an InitRng(seed string) at Curve level (and commented out the use of HashToGroup).
GoApis (go run -tags=z3,miracl examples/ex_GoAPI_noservice_noz3.go) should be fine (I'll check JsonApis asap for serialization issues).

Anyway, about the secret: this is a pairing-based cryptography, say the pairing being G1 x G2 -> GT.
The secret is a point on GT which is (randomly) perturbed by encryption into a ciphertext and (possibly) reconstructed by decryption.
It is not conceptually a random point on GT (that's why an hint for hash-to-group was there),
but it is often useful to pick it as a random point on GT.

**Comment by yujingyue9166** [comment]
Thanks a lot. It is really helpful.
